name:                tetriskell
version:             0.1.0.0
github:              "harryaskham/tetriskell"
license:             BSD3
author:              "Harry Askham"
maintainer:          "harry@askham.ai"
copyright:           "2019 Harry Askham"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/harryaskham/tetriskell#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- hidden-char
- random
- vector
- split
- parallel
- utility-ht

library:
  source-dirs: src

executables:
  tetriskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetriskell
